config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  resources :tests

  get     '/company_dashboard/',  to: "dashboard#company"
  get     '/user_dashboard/',     to: "dashboard#user"
  get     '/profile/:id',          to: "dashboard#profile"

  get     '/visas/',              to: "visas#index"
  get     '/visas/:id',           to: "visas#show",           as: "visa"

  get     '/stamps/',             to: "stamps#index"
  post    '/stamps/',             to: "stamps#create",        as: "stamp_create"
  get     '/stamps/:id/payment',  to: "stamps#payment",       as: "payment"
  post    '/stamps/:id/',         to: "stamps#check_payment", as: "check_payment"
  get     '/stamps/:id/',         to: "stamps#show",          as: "stamp"
  post    '/stamps/:id/start',    to: "stamps#start_test",    as: "start_test"
  post    '/stamps/:id/finish',   to: "stamps#finish_test",   as: "finish_test"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stamp.rb
class Stamp < ApplicationRecord
  belongs_to :user
  belongs_to :test
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :user
  belongs_to :visa
  has_many :stamps

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :stamps
  # has many stamps through code_reviews
  has_one_attached :avatar
end

app/models/visa.rb
class Visa < ApplicationRecord
  has_many :tests
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: [:index, :user, :company, :profile], unless: :skip_pundit?
  after_action :verify_policy_scoped, only: [:index, :user, :company, :profile], unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end


  before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
      # For additional fields in app/views/devise/registrations/new.html.erb
      devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :role, :name, :cpf])

      # For additional in app/views/devise/registrations/edit.html.erb
      devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :role, :name, :cpf])
    end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :profile ]

  def user
    @user = current_user
    @tests = policy_scope(Test).where(user: current_user).order(created_at: :desc)
  end

  def company
    @tests = policy_scope(Test).where(user: current_user).order(created_at: :desc)
  end

  def profile
    @user = policy_scope(User).find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/stamps_controller.rb
class StampsController < ApplicationController
  before_action :set_stamp, only: [:payment, :show, :check_payment, :start_test, :finish_test]
  skip_before_action :verify_authenticity_token, only: [:check_payment]

  def create
    @stamp = Stamp.new
    authorize @stamp

    @stamp.user_id = params["user"]
    @stamp.test_id = params["test"]
    @stamp.start_date = Date.today
    # nao eh!! precisa modificar para ser a data onde usuario clica em "start test"
    @stamp.deadline_date = Date.today + 7
    @stamp.status = 0
    @stamp.save

    redirect_to payment_path(@stamp)
  end

  def payment
    redirect_to check_payment_path
  end

  def check_payment
    @stamp.status = 1
    @stamp.save
    redirect_to stamp_path(@stamp)

  end

  def show
  end

  def start_test
    @stamp.status = 2
    @stamp.save
    redirect_to stamp_path(@stamp)
  end

  def finish_test
    @stamp.status = 3
    @stamp.save
    puts "oiii"
    redirect_to stamp_path(@stamp)
  end

  private

  def set_stamp
    @stamp = Stamp.find(params[:id])
    authorize @stamp
  end
end

app/controllers/testes_controller.rb
class TestesController < ApplicationController
  def new
    @test = current_user.test.new
    authorize @test
  end

  def create
    @test = current_user.test.new(test_params)
    authorize @test
    if @test.save
    redirect_to test_path(@test)
  end

  def edit
  end

  def destroy
    @test = Test.find(params[:id])
    @tests.destroy (test_params)
    redirect_to test_path
  end

  def set_test
    @test = Test.find(params[:id])
    authorize @test
  end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController

  before_action :set_test, only: [:edit, :update, :destroy]

  def index
    @tests = policy_scope(Test).order(created_at: :desc)
  end

  def new
    @test = Test.new
    authorize @test
  end

  def create
    @test = Test.new(test_params)
    @test.user = current_user
    authorize @test

    if @test.save
      redirect_to company_dashboard_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    @test.update(test_params)
    redirect_to company_dashboard_path
  end

  def destroy
    @test.destroy
    redirect_to company_dashboard_path
  end

  def set_test
    @test = Test.find(params[:id])
    authorize @test
  end

  private
  def test_params
    params.require(:test).permit(:title, :description, :seniority, :visa_id)
  end
end

app/controllers/visas_controller.rb
class VisasController < ApplicationController
  before_action :set_visa, only: [:show]
  skip_before_action :authenticate_user!, only: [ :index, :show ]

  def index
    @visas = policy_scope(Visa)
  end

  def show
  end

  private

  def set_visa
    @visa = Visa.find(params[:id])
    authorize @visa
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dashboard/company.html.erb
<div class="col-12 no-padding mb-5">
  <%= image_tag("nubank_banner-8.jpg", class: "d-block w-75 banner-home", style: 'object-fit: cover; margin: 0 auto; height: 400px', alt: "Nubank") %>
</div>

<div class="container">

  <div class="col-sm-12 text-center mt-5 mb-5">
    <h2>Developers' Performance</h3>
  </div>


<div class="d-flex justify-content-center">
  <div class="row">
    <div class="col-sm-6">
      <%= image_tag "OverviewNew.png" %>
    </div>
    <div class="col-sm-6 mb-5">
     <%= image_tag "History.png" %>
    </div>
  </div>
</div>

<div class="col-sm-12 text-center mt-5 mb-5">
  <h3>The latest <strong>DevPassport developers</strong> who completed your tests</h3>
</div>

<div class="row justify-content-center">
  <div class="col-sm-8 mb-5">
    <div class="card-deck">

      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Allan P. Turing</h5>
          <p class="card-text">"Clojure Test" - Out/2020</p>

        </div>
      </div>

      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Walter S. Jobs</h5>
          <p class="card-text">"React" - Nov/2020</p>
        </div>
      </div>

      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Vivian A. Gates</h5>
          <p class="card-text">"Clojure Test" - Nov/2020</p>
        </div>
      </div>


      <div class="card text-white bg-dark mb-3" style="max-width: 18rem;">
        <div class="card-body">
          <h5 class="card-title">Paulo O. Musk</h5>
          <p class="card-text">"React" - Dez/2020</p>
        </div>
      </div>

    </div>
  </div>
</div>

<div class="col-sm-12 text-center mt-5 mb-5">
  <h2>All your <strong>Dev Tests</strong> available</h3>
</div>

<div class="row mb-5">
  <% @tests.each do |test| %>
    <div class="col-sm-6 mb-5">
      <h2 style="color: orange" align-item: center>
        <%= test.title %>
      </h2>
      <h3>
        <%= test.seniority %>
      </h3>
      <p>
        <%= test.description %>
      </p>
    </div>
  <% end %>
</div>
</div>

<div class="row justify-content-center mt-5">
  <div class="col-sm-12 text-center">
    <h2>Create a new test</h2>
    <br>
    <h4> Choose the <strong>Back-End</strong> test language</h4>
    <div class="d-flex flex-wrap justify-content-center pt-4">

      <div class="clickable">
        <i class="fab fa-python"></i>
        <small>Python</small>
      </div>
      <div class="clickable">
        <i class="fab fa-node"></i>
        <small>Node js</small>
      </div>
      <div class="clickable">
        <i class="fab fa-java"></i>
        <small>Java</small>
      </div>
      <div class="clickable">
        <i class="fab fa-php"></i>
        <small>PHP</small>
      </div>
      <div class="clickable">
        <i class="fas fa-server"></i>
        <small>PostgreSQL</small>
      </div>
      <div class="clickable">
        <i class="fab fa-github-square"></i>
        <small>Github</small>
      </div>
    </div>

  </div>
</div>

<div class="row justify-content-center mt-5">
  <div class="col-sm-12 text-center" style="height: 300px">
    <h4>Choose the <strong>Front-End</strong> test language</h4>
    <div class="d-flex flex-wrap justify-content-center pt-4">

      <div class="clickable">
        <i class="fab fa-html5"></i>
        <small>HTML</small>
      </div>
      <div class="clickable">
        <i class="fab fa-css3-alt"></i>
        <small>CSS</small>
      </div>
      <div class="clickable">
        <i class="fab fa-js-square"></i>
        <small>JavaScript</small>
      </div>
      <div class="clickable">
        <i class="fab fa-react"></i>
        <small>React</small>
      </div>
      <div class="clickable">
        <i class="fab fa-vuejs"></i>
        <small>Vue js</small>
      </div>
      <div class="clickable">
        <i class="fab fa-angular"></i>
        <small>Angular</small>
      </div>
    </div>
  </div>

<div class="col-sm-12 text-center" style="height: 200px">
<div class="btn btn-primary btn-rounded">
  <%= link_to "Create New Test", new_test_path %>
</div>
</div>

app/views/dashboard/profile.html.erb
<div class="container">


  <div class="avatar-large" style="background-image: url(<%= cl_image_path @user.avatar.key %>);">
  </div>


  <h1 class="text-center"><%= @user.name %>'s DevPassport</h1>


  <h2>Stamps Granted</h2>

  <div class="profile-block">
    <div class="row">
      <% @user.stamps.each do |stamp| %>
        <div class="col-sm-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-title">
                <%= stamp.test.visa.title %>
              </h5>
              <p class="card-text">With
                <%= stamp.test.title %> from <%= stamp.test.user.name %>
              </p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <h2>Contact Information</h2>
  <div class="profile-block">
    <div class="card p-2">
      <p>Email: <strong><%= @user.email %></strong></p>
    </div>
    <div class="card p-2">
      <p>Telephone: <strong>+55 11 98276 2220</strong></p>
    </div>
    <div class="card p-2">
      <p>LinkedIn: <strong><a href="#"><%= @user.name %></a></strong></p>
    </div>
  </div>
</div>

app/views/dashboard/user.html.erb
<% def status_name(index) %>
<%  hash = { 0 => "payment pending", 1 => "payment approved", 2 => "test started", 3 => "test completed", 4 => "stamp granted", 5 => "stamp not granted" } %>
<%  return hash[index] %>
<% end %>


<h1>Dashboard</h1>

  <h2>This is you</h2>

  <ul>
    <li>Name: <%= @user.name %></li>
    <li>Email: <%= @user.email %></li>
    <li>CPF: <%= @user.cpf %></li>
  </ul>


<!-- STAMPS -->
<% stamps = @user.stamps.select { |stamp| stamp.status == 4 } %>

<% unless stamps.empty? %>
  <h2>These are your stamps!</h2>
<% end %>

<% stamps.each do |stamp|  %>
  <h3>
    <%= link_to stamp.test.title, stamp_path(stamp) %>
  </h3>
  <ul>
    <li>
      Status: <%= status_name(stamp.status) %>
    </li>
    <li>
      Start date: <%= stamp.start_date %>
    </li>
    <li>
      Deadline: <%= stamp.deadline_date %>
    </li>
    <li>
      <%= link_to "Click here to start your test", start_test_path(stamp), method: "post" %>
    </li>
  </ul>
<% end %>




<!-- TESTS NOT STARTED -->
<% stamps = @user.stamps.select { |stamp| stamp.status == 0 || stamp.status == 1 } %>

<% unless stamps.empty? %>
  <h2>Tests you haven't started yet:</h2>
<% end %>

<% stamps.each do |stamp|  %>
  <h3>
    <%= link_to stamp.test.title, stamp_path(stamp) %>
  </h3>
  <ul>
    <li>
      Status: <%= status_name(stamp.status) %>
    </li>
    <li>
      Start date: <%= stamp.start_date %>
    </li>
    <li>
      Deadline: <%= stamp.deadline_date %>
    </li>
    <li>
      <%= link_to "Click here to start your test", start_test_path(stamp), method: "post" %>
    </li>
  </ul>
<% end %>


<!-- OTHER TESTS -->
<% stamps = @user.stamps.select { |stamp| stamp.status != 0 && stamp.status != 1 && stamp.status != 4  } %>

<% unless stamps.empty? %>
  <h2>Other tests:</h2>
<% end %>

<% stamps.each do |stamp|  %>
  <h3>
    <%= link_to stamp.test.title, stamp_path(stamp) %>
  </h3>
  <ul>
    <li>
      Status: <%= status_name(stamp.status) %>
    </li>
    <li>
      Start date: <%= stamp.start_date %>
    </li>
    <li>
      Deadline: <%= stamp.deadline_date %>
    </li>
    <li>
      <%= link_to "Click here to start your test", start_test_path(stamp), method: "post" %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DevPassport</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>

  </body>
</html>

app/views/pages/home.html.erb
 <div class="d-flex justify-content-around home-banner">
  <div class="w-100 justify-content-center">
    <h1>DevPassport</h1>
    <p>
      <span id="banner-typed-text"></span>
    </p>
    <div class="justify-content-end">
      <%= link_to "View all our visas", visas_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

<div id="devCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#devCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#devCarousel" data-slide-to="1"></li>
    <li data-target="#devCarousel" data-slide-to="2"></li>
    <li data-target="#devCarousel" data-slide-to="3"></li>
    <li data-target="#devCarousel" data-slide-to="4"></li>
  </ol>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag("Capa_Video_banner.jpg", class: "d-block w-100 banner-home", style: 'object-fit: cover', alt: "First slide") %>

      <div class="container">
        <div class="carousel-caption d-none d-md-block font-carousel">
          <h2>DevPassport Stamps™</h2>
          <p>
            A DevPassport stamp is the most trustful developer certification, according to Gartner's Magic Quadrant - Innovative Solutions 2020
          </p>
        </div>
      </div>
    </div>

    <div class="carousel-item">

      <%= image_tag("casal_luzes.jpg", class: "d-block w-100 banner-home", style: 'object-fit: cover; background-color: linear-gradient(rgba(0,0,0,0.5), rgba(0,0,0,0.5));', alt: "Second slide") %>

      <div class="container">
        <div class="carousel-caption d-none d-md-block font-carousel">
          <h1>Nubank MoonShoot Stamp™</h1>
          <p>
            Apply for the DevPassport Front-end stamp and become one of the most qualified candidates for the Nubank technical assessment...
          </p>

        </div>
      </div>
    </div>

    <div class="carousel-item">
      <%= image_tag("pcd.jpg", class: "d-block w-100 banner-home", style: 'object-fit: cover', alt: "Third slide") %>

      <div class="container">
        <div class="carousel-caption d-none d-md-block font-carousel">
          <h1>Shopify Rubicon Stamp™</h1>
          <p>
            The Shopify Developer's stamp allows you to go straight to technical interview in 89% of the biggest companies on the planet!
          </p>

        </div>
      </div>
    </div>

    <div class="carousel-item">
      <%= image_tag("girl_server.jpg", class: "d-block w-100 banner-home", style: 'object-fit: cover', alt: "Third slide") %>

      <div class="container">
        <div class="carousel-caption d-none d-md-block font-carousel">
          <h1>Stone High Profile Stamp™</h1>
          <p>
            Considered as one of the most critical and complex developer's assessment processes.  DevPassport Stone stamp sealed you to go straight to Soft skills test!
          </p>

        </div>
      </div>
    </div>

    <div class="carousel-item">
      <%= image_tag("3bwomen.jpg", class: "d-block w-100 banner-home", style: 'object-fit: cover', alt: "Third slide") %>

      <div class="container">
        <div class="carousel-caption d-none d-md-block font-carousel">
          <h1>Le Wagon Brave Coding Stamp™</h1>
          <p>
            Learn about the best practices of innovative coding skills!
          </p>

        </div>
      </div>
    </div>

  </div>

    <a class="carousel-control-prev" href="#devCarousel" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#devCarousel" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div>

    <div class="visas">
     <h2>Companies that trust in our stamps</h2>
    </div>

      <div class="cards-visa">

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.5)), url(<%= image_path 'stone.png' %>)">
        </div>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.5)), url(<%= image_path 'logo-nubank-roxo-256.png' %>)">
        </div>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.5)), url(<%= image_path 'lewagon.png' %>)">
        </div>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.5)), url(<%= image_path 'shopify-logo-hd-1.png' %>)">
        </div>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.5)), url(<%= image_path 'mercado-livre-2.png' %>)">
        </div>

      </div>



      <div class="col-md-12 col-lg-12 vhm no-padding" style="background:url(<%= image_path 'report-candidate.png' %>) 50% 50% no-repeat;background-attachment:fixed;background-size:cover">
        <div class="evi text-center mt-5">
          <h3>Raising the hiring bar for software developers while simultaneously eliminating bias, is key to accelerate the world's innovation!</h3>
        </div>
      </div>

      <div class="d-flex justify-content-around home-success-banner">
        <div>
          <h1></h1>
          <p></p>
        </div>
      </div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm sticky-top navbar-dark navbar-lewagon border-info">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "passport-logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>

      <% if user_signed_in? %>

        <li class="nav-item">
          <% if current_user.role == 3 %>
            <%= link_to current_user.name, company_dashboard_path, class: "nav-link"  %>
          <% else %>
            <%= link_to current_user.name, user_dashboard_path, class: "nav-link"  %>
          <% end %>
        </li>

        <li class="nav-item dropdown">
          <% if current_user.avatar.present? %>
            <%= cl_image_tag current_user.avatar.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "avatar_muslim.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>

          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>

        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>

      <% end %>

    </ul>

  </div>
</div>

app/views/stamps/_stamp_view1.html.erb
<div class="container stamp-main-area">
  <div class="row">
    <div class="col-5 p-0 stamp-info">
      <div class="stamp-head-img w-100 mb-4"></div>

      <h4>
        <%=@stamp.test.title%>
        <%if @stamp.status >= 2 %>
        <div class="stamp-due-date">
          <p>You have until <%= 7.days.from_now.strftime("%Y-%m-%d") %> to finish the project! </p>
        </div>
        <%end%>
        <div class="stamp-actions">
          <p><%= link_to "Start Test", start_test_path, method: "post", class: "btn btn-primary btn-rounded"%></p>
          <%if @stamp.status == 2 %>
          <p> <%= link_to  "Open Your Test", @stamp.test.link, class: "btn btn-info btn-rounded" %></p>
          <p> <%= link_to  "Finish Test", finish_test_path, method: "post", class: "btn btn-danger btn-rounded" %></p>
          <%elsif @stamp.status < 2%>
          <p> <%= link_to  "Open Your Test", '', class: "btn btn-secondary disabled btn-rounded" %></p>
          <p> <%= link_to  "Finish Test", '', class: "btn btn-secondary disabled btn-rounded" %></p>

          <%end%>
        </div>



        <!-- mudar status de 1 para 2 -->
        <!-- se status = 2 -->

        <!-- mostrar aqui formulario para test_answer -->
        <!-- mostrar submit button -->
        <!-- mostrar data limite para terminar o teste -->
        <!-- mudar status para 3 -->
        <br>
        <br>
        <br>
        <br>
    </div>
    <div class="col-7 stamp-border-left">
      <div class="stamp-instructions w-75">
        <h2>Instructions:</h2>
        <ol>
          <li>When you click Start, you'll have 7 calendar days to complete the test. A link to the GitHub repository where the test is located will be opened, you must fork it. </li>
          <br>
          <div class="icon-instructions">
            <img src="https://img.icons8.com/wired/64/FFFFFF/code-fork.png" />
          </div>
          <br>
          <li>Follow the instructions in the readme to complete the test. </li>
          <br>
          <div class="icon-instructions">
            <i class="fab fa-readme fa-4x"></i>
          </div>
          <br>
          <li>Put on your headphones and do your best! When you're done, click in "Finish Test"</li>
          <br>
          <div class="icon-instructions">
            <i class="fas fa-headphones fa-4x"></i>
          </div>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/stamps/edit.html.erb
<h1>Edit your stamp:</h1>

<%= form_for(@stamp) do |f| %>
<%= f.label :issuing_date %>
<%= f.text_field :issuing_date %>

<%= f.label :expiration_date %>
<%= f.text_field :expiration_date %>

<%= f.submit %>
<% end %>

app/views/testes/edit.html.erb
<h1>Edit your test:</h1>

<%= form_for(@test) do |f| %>
<%= f.label: title %>
<%= f.text_field: title %>

<%= f.label: description %>
<%= f.text_field: description %>

<%= f.submit %>
<% end %>

app/views/visas/index.html.erb
<% images = ["front-end.png", "back-end.jpg", "full-stack.png", "mobile.png", "data.jpg"] %>


<div class="container">
  <h1 class="text-center">Our Visas for You</h1>

  <% @visas.each_with_index do |visa, i| %>

    <div class="card-visa bg-dark">


      <%= image_tag images[i] %>

      <div>
        <h2>
          <%= link_to visa.title, visa_path(visa) %>
        </h2>
        <p>
          <%= visa.description %>
        </p>
      </div>
    </div>

  <% end %>
</div>

app/views/visas/show.html.erb
<div class="container">
  <h1 class="text-center">
    These are the <%= @visa.title %> tests
  </h1>

  <% @visa.tests.each do |test| %>

    <div class="card-test d-flex bg-dark">

      <%= cl_image_tag test.user.avatar.key, class: "", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

      <div class="flex-grow-1">
        <h2>
          <%= test.user.name  %> - <%= test.title %>
        </h2>
        <p>
          <%= test.description %>
        </p>
      </div>

      <div class="mr-3 details">
        <p class="">Seniority Level: <%= test.seniority %></p>
        <p>Price: R$ <%= test.price %>,00 </p>
        <%= link_to "Comprar", stamp_create_path(user: current_user, test: test), method: :post, class:"btn btn-primary btn-small" %>
      </div>

    </div>
  <% end %>
</div>

  <!-- <div class="card-trip">
    <#%= image_tag("keyb-banner.jpg", style: 'object-fit: cover') %>
    <div class="card-trip-infos">
      <div>
        <h2><#%= test.title %></h2>
        <ul>
          <li>Author: <#%= test.user.name  %></li>
          <li>Description: <#%= test.description %></li>
          <li>Seniority: <#%= test.seniority %></li>
          <#%= link_to "Comprar", stamp_create_path(user: current_user, test: test), method: :post, class:"btn btn-primary" %>
        </ul>
      </div>
      <h2 class="card-trip-pricing"><#%= test.price %></h2>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
    </div>
  </div>

</div>
 -->